### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by Shizzlebix** [NightMan-1/netatmo-munin-go#3]
munin-run netatmo-munin-plugin:

**panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47da03]

goroutine 1 [running]:
panic(0x6345a0, 0xc42000c0e0)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/exzz/netatmo-api-go.(*Device).Data(0xc42040a0e0, 0xc4201132c0, 0x6)
	/root/netatmo-api-go/src/github.com/exzz/netatmo-api-go/weather.go:278 +0x953
main.main()
	/root/netatmo-munin-go/netatmo-munin-plugin.go:93 +0x501**
	
Can you please take a look? T@x

**Comment by NightMan-1** [comment]
The problem is somewhere here - https://github.com/exzz/netatmo-api-go/pull/8 - something has changed in NetAtmo API, unfortunately I do not have time now and will not be able to fix it quickly :(

**Comment by Shizzlebix** [comment]
found the problem... if module "niederschlagsmesser" not avaible the error comes....
after restart my netatmo the module is avaible and all is fine

**Comment by Shizzlebix** [comment]
Hello,
the problem is.... if a device of netatmo is offline then the error is coming.
if all devices are online no error is there.
